bump

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -47,46 +47,46 @@ branding:
 runs:
   using: "composite"
   steps:
-    # - name: Set translation paths
-    #   id: translation-paths
-    #   shell: bash
-    #   env:
-    #     TRANSLATIONS_PATH: "${{ inputs.translations_path }}"
-    #     FLAT_NAMING: "${{ inputs.flat_naming }}"
-    #     BASE_LANG: "${{ inputs.base_lang }}"
-    #     FILE_FORMAT: "${{ inputs.file_format }}"
-    #   run: |
-    #     set -e
+    - name: Set translation paths
+      id: translation-paths
+      shell: bash
+      env:
+        TRANSLATIONS_PATH: "${{ inputs.translations_path }}"
+        FLAT_NAMING: "${{ inputs.flat_naming }}"
+        BASE_LANG: "${{ inputs.base_lang }}"
+        FILE_FORMAT: "${{ inputs.file_format }}"
+      run: |
+        set -e
 
-    #     CMD_PATH="${{ github.action_path }}/bin/store_translation_paths"
-    #     chmod +x "$CMD_PATH"
-    #     $("$CMD_PATH") || {
-    #       echo "Error: store_translation_paths script failed with exit code $?"
-    #       exit 1
-    #     }
+        CMD_PATH="${{ github.action_path }}/bin/store_translation_paths"
+        chmod +x "$CMD_PATH"
+        $("$CMD_PATH") || {
+          echo "Error: store_translation_paths script failed with exit code $?"
+          exit 1
+        }
 
-    # - name: Get changed files
-    #   id: changed-files
-    #   uses: tj-actions/changed-files@v45
-    #   with:
-    #     files_from_source_file: paths.txt
-    #     separator: ','
+    - name: Get changed files
+      id: changed-files
+      uses: tj-actions/changed-files@v45
+      with:
+        files_from_source_file: paths.txt
+        separator: ','
 
-    # - name: Check if this is the first run on the branch
-    #   if: steps.changed-files.outputs.any_changed == 'false'
-    #   id: check-first-run
-    #   shell: bash
-    #   run: |
-    #     set -e
+    - name: Check if this is the first run on the branch
+      if: steps.changed-files.outputs.any_changed == 'false'
+      id: check-first-run
+      shell: bash
+      run: |
+        set -e
 
-    #     if git rev-parse "refs/tags/lokalise-upload-complete" >/dev/null 2>&1; then
-    #       echo "first_run=false" >> $GITHUB_OUTPUT
-    #     else
-    #       echo "first_run=true" >> $GITHUB_OUTPUT
-    #     fi
+        if git rev-parse "refs/tags/lokalise-upload-complete" >/dev/null 2>&1; then
+          echo "first_run=false" >> $GITHUB_OUTPUT
+        else
+          echo "first_run=true" >> $GITHUB_OUTPUT
+        fi
 
     - name: Find all translation files
-      # if: steps.changed-files.outputs.any_changed == 'false' && steps.check-first-run.outputs.first_run == 'true'
+      if: steps.changed-files.outputs.any_changed == 'false' && steps.check-first-run.outputs.first_run == 'true'
       id: find-files
       shell: bash
       env:
@@ -103,13 +103,6 @@ runs:
           echo "Error: find_all_files script failed with exit code $?"
           exit 1
         }
-
-    - name: Debug GitHub Output
-      shell: bash
-      run: |
-        ALL_FILES="${{ steps.find-files.outputs.ALL_FILES }}"
-        echo "Contents of GITHUB_OUTPUT:"
-        echo "$ALL_FILES"
 
     - name: Install Lokalise CLI
       if: steps.find-files.outputs.has_files == 'true' || steps.changed-files.outputs.any_changed == 'true'
@@ -130,13 +123,11 @@ runs:
       run: |
         set -e
 
-        # if [ "${{ steps.check-first-run.outputs.first_run }}" == "true" ]; then
-        #   FILES="${{ steps.find-files.outputs.ALL_FILES }}"
-        # else
-        #   FILES="${{ steps.changed-files.outputs.all_changed_files }}"
-        # fi
-
-        FILES="${{ steps.find-files.outputs.ALL_FILES }}"
+        if [ "${{ steps.check-first-run.outputs.first_run }}" == "true" ]; then
+          FILES="${{ steps.find-files.outputs.ALL_FILES }}"
+        else
+          FILES="${{ steps.changed-files.outputs.all_changed_files }}"
+        fi
 
         if [ -z "$FILES" ]; then
           echo "No files to upload."
@@ -155,17 +146,17 @@ runs:
           exit 1
         fi
 
-    # - name: Mark Lokalise upload as complete
-    #   if: steps.check-first-run.outputs.first_run == 'true'
-    #   shell: bash
-    #   run: |
-    #     set -e
+    - name: Mark Lokalise upload as complete
+      if: steps.check-first-run.outputs.first_run == 'true'
+      shell: bash
+      run: |
+        set -e
 
-    #     git config --global user.name "${GITHUB_ACTOR}"
-    #     git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
-    #     if ! git rev-parse "refs/tags/lokalise-upload-complete" >/dev/null 2>&1; then
-    #       git tag -a "lokalise-upload-complete" -m "First Lokalise upload complete"
-    #       git push origin "lokalise-upload-complete"
-    #     else
-    #       echo "Tag 'lokalise-upload-complete' already exists."
-    #     fi
+        git config --global user.name "${GITHUB_ACTOR}"
+        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
+        if ! git rev-parse "refs/tags/lokalise-upload-complete" >/dev/null 2>&1; then
+          git tag -a "lokalise-upload-complete" -m "First Lokalise upload complete"
+          git push origin "lokalise-upload-complete"
+        else
+          echo "Tag 'lokalise-upload-complete' already exists."
+        fi
